### ISSUE TITLE
The difference to original implementation

### ISSUE THREAD

**Issue by 87003697** [nipunjindal/diffusers-layout-guidance#1]
Hi, thank you for your effort in merging the training-free layout control to diffusers! I'm interested in learning more about how your implementation differs from the official version. Is there a reference available that outlines the specific changes you made? Having a guide to the modifications in your implementation compared to the original would be helpful as a reference point for me to better understand your approach. Thanks!

**Comment by nipunjindal** [comment]
Hi @87003697,

There isn't a difference of logic from the paper or deviation from it. The main aim of the repo is to adapt to diffusers which then allows to try all the different features present within diffusers like multiple scheduler. Hope that makes sense.
